import { library } from "@fortawesome/fontawesome-svg-core";
import { fab } from "@fortawesome/free-brands-svg-icons";
import {
  faEnvelope,
  faLock,
  faUser,
  faUsers,
  faCartShopping,
  faArrowRotateLeft,
  faPlus,
  faPencil,
  faTrash,
  faCircleUser,
  faWarehouse,
  faScaleBalanced,
  faBusinessTime,
  faSitemap,
  faCertificate,
  faRecycle,
  faSquare,
  faChartLine,
  faFileExcel,
  faLayerGroup,
  faUniversalAccess,
  faSackDollar
} from "@fortawesome/free-solid-svg-icons";

library.add(
  fab,
  faEnvelope,
  faLock,
  faUser,
  faUsers,
  faCartShopping,
  faArrowRotateLeft,
  faPlus,
  faPencil,
  faTrash,
  faCircleUser,
  faWarehouse,
  faScaleBalanced,
  faBusinessTime,
  faSitemap,
  faCertificate,
  faRecycle,
  faSquare,
  faChartLine,
  faFileExcel,
  faLayerGroup,
  faUniversalAccess,
  faSackDollar
);
